config/routes.rb
Rails.application.routes.draw do
  resources :form_editables
  devise_for :admins
  root :to => 'people#new'

  resources :people do
    resources :jobs
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/person.rb
class Person < ApplicationRecord
  has_many :jobs
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  layout :resolve_layout
  before_action :authenticate_admin!, except: [:new, :create]
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @fe = FormEditable.last
    @people = Person.all.order(created_at: :desc).limit(25)
  end

  # GET /people/1
  # GET /people/1.json
  def show
    @fe = FormEditable.last
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.find_or_initialize_by(email: person_params[:email])
    @person.assign_attributes(person_params)

    respond_to do |format|
      if @person.save
        # UserMailer.with(person: @person).results_email.deliver_now
        format.html { redirect_to new_person_job_path(person_id: @person.id) }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :phone, :email, :address, :time_at_address)
    end

    def resolve_layout
      case action_name
      when "new"
        "customer_layout"
      else
        "application"
      end

    end
end

app/helpers/people_helper.rb
module PeopleHelper
  def approval_statement(approved)
    if approved
      "Pre-Approved"
    else
      "In For Review"
    end
  end

  def customer_approval_statement(approved)
    if approved
      render 'customer_pre-approved'
    else
      render 'customer_in_for_review'
    end
  end
end

app/views/people/_form.html.erb
<%= form_with(model: person, local: true) do |form| %>
  <% if person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.telephone_field :phone %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :time_at_address %>
    <%= form.select :time_at_address, ((0..500).map) %>Months
  </div>

  <div class="actions">
    <%= form.submit "Next"%>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form', person: @person %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>People</h1>

<table id="table1">
  <thead>
    <tr>
      <th>Name</th>
      <th>Phone</th>
      <th>Email</th>
      <th>Submitted On</th>
      <th>Approval</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= person.phone %></td>
        <td><%= person.email %></td>
        <td><%= person.created_at.strftime("%b. %d, %Y") %></td>
        <td><%= approval_statement(person.jobs.last.approved?(@fe.down_payment_percentage, @fe.max_payment_amount_limit, @fe.months, @fe.interest)) if person.jobs.present? %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Edit Form', edit_form_editable_path(@fe) %>

app/views/people/new.html.erb
<h1>Check for Your Pre-Approval Now!</h1>

<%= render 'form', person: @person %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p>
  Name: <%= @person.name %>
</p>

<p>
  Phone: <%= @person.phone %>
</p>

<p>
  Email: <%= @person.email %>
</p>

<p>
  Address: <%= @person.address %>
</p>

<p>
  Time At Address: <%= @person.time_at_address %>
</p>


<%= render 'jobs/table', jobs: @person.jobs %>

<%= link_to 'New', new_person_job_path(person_id: @person.id) %>

<%= link_to 'Back', people_path %>