config/routes.rb
Rails.application.routes.draw do
  resources :form_editables
  devise_for :admins
  root :to => 'people#new'

  resources :people do
    resources :jobs
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/job.rb
class Job < ApplicationRecord
  belongs_to :form_editable
  belongs_to :person
  validates :monthly_income, :down_payment, numericality: {greater_than: 0}

  def car_price(dpp)
    down_payment / dpp
  end

  def max_payment_amount(mpal)
    monthly_income / mpal
  end

  def average_payment(dpp, m, i)
    (car_price(dpp) / m) + i
  end

  def approved?(dpp, mpal, m, i) # methods ending in "?" return true or false
    average_payment(dpp, m, i) < max_payment_amount(mpal)
  end

end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  layout :resolve_layout
  before_action :authenticate_admin!, except: [:new, :create, :show]
  before_action :set_job, only: [:show, :edit, :update, :destroy]

  # GET /jobs
  # GET /jobs.json
  def index
    @fe = FormEditable.last
    @jobs = Job.all
    @person = params["person_id"]
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    @fe = FormEditable.last
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "Car_Approval_Results",
        template: "jobs/show.html.erb",
        locals: {:job => @job}
      end
    end
  end

  # GET /jobs/new
  def new
    @job = Job.new
    @person = params["person_id"]
  end

  # GET /jobs/1/edit
  def edit
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)
    @job.person_id = params["person_id"]

    respond_to do |format|
      if @job.save
        format.html { redirect_to person_job_path(@job.person_id, @job) }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /jobs/1
  # PATCH/PUT /jobs/1.json
  def update
    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { render :show, status: :ok, location: @job }
      else
        format.html { render :edit }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job.destroy
    respond_to do |format|
      format.html { redirect_to person_url, notice: 'Job was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job
      @job = Job.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:name, :months_at, :monthly_income, :down_payment, :person_id)
    end

    def resolve_layout
      case action_name
      when "new", "create"
        "customer_layout"
      when "show"
        "pdf"
      else
        "application"
      end
    end

end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/_customer_in_for_review.html.erb
We'll get back to you as soon as we could!

app/views/jobs/_customer_pre-approved.html.erb
<title>Preapproval Results</title>

<h1>Company Name</h1><br>

<h2>Dear <%= @job.person.name %>,</h2>

Congratulations on your preapproval!

<p>
  This preapproval amount is based on a review of the monthly income and asset information you provided, which is subject to a formal underwriting review.
</p>

Loan Terms:
<ul>
  <li>Purchase Price: $<%= number_with_delimiter(@job.car_price.round(0), :delimiter => ",") %></li>
  <li>Down Payment: $<%= number_with_delimiter(@job.down_payment.round(0), :delimiter => ",") %></li>
  <li>Loan Amount: $<%= number_with_delimiter(@job.average_payment.round(0), :delimiter => ",") %></li>
</ul>
<p>
  At Company Name, we're commited to making your car purchase experience as smooth as possible. If you have any questions regarding this preapproval, please don't hesitate to give me a call at (666) 666-6666.
</p>

<p>
  I look forward to helping you finance your new car.
</p>

<p>
  Sincerely,
</p>

<p>
  Employee Name<br>
  Employee Position
</p><br>

<p>
Tel: (666) 666-6666<br>
Fax: (666) 666-6666<br>
Email: employeename@company.com
</p>

app/views/jobs/_form.html.erb
<%= form_with(model: @job, url: person_jobs_path) do |form| %>
  <% if job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% job.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :job %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :months_at %>
    <%= form.select :months_at, ((0..500).map) %>Months
  </div>

  <div class="field">
    <%= form.label :monthly_income %>
    <%= form.text_field :monthly_income %>
  </div>

  <div class="field">
    <%= form.label :down_payment %>
    <%= form.text_field :down_payment %>
  </div>

  <div class="actions">
    <%= form.submit "Submit"%>
  </div>

<% end %>

app/views/jobs/_table.html.erb
<table id="table1">
  <thead>
    <tr>
      <th>Job</th>
      <th>Months At</th>
      <th>Monthly Income</th>
      <th>Car Downpayment</th>
      <th>Approval</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% jobs.each do |job| %>
      <tr>
        <td><%= job.name %></td>
        <td><%= job.months_at %></td>
        <td>$<%= number_with_delimiter(job.monthly_income, :delimiter => ",") %>/m</td>
        <td>$<%= number_with_delimiter(job.down_payment, :delimiter => ",") %></td>
        <td><%= approval_statement(job.approved?(@fe.down_payment_percentage, @fe.max_payment_amount_limit, @fe.months, @fe.interest)) if job.present? %></td>
        <td></td>
        <td></td>
        <td></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/jobs/edit.html.erb
<h1>Editing Job</h1>

<%= render 'form', job: @job %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', person_jobs_path %>

app/views/jobs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Jobs</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @jobs.each do |job| %>
      <tr>
        <td><%= link_to 'Show', @person.job %></td>
        <td><%= link_to 'Edit', edit_job_path(job) %></td>
        <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Job', new_person_job_path %>

app/views/jobs/new.html.erb
<%= render 'form', job: @job %>

app/views/jobs/show.html.erb
<%= customer_approval_statement(@job.approved?(@fe.down_payment_percentage, @fe.max_payment_amount_limit, @fe.months, @fe.interest)) if @job.present? %>