config/routes.rb
Rails.application.routes.draw do
  resources :form_editables
  devise_for :admins
  root :to => 'people#new'

  resources :people do
    resources :jobs
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/form_editables_controller.rb
class FormEditablesController < ApplicationController
  before_action :set_form_editable, only: [:show, :edit, :update, :destroy]

  # GET /form_editables
  # GET /form_editables.json
  def index
    @form_editables = FormEditable.all
  end

  # GET /form_editables/1
  # GET /form_editables/1.json
  def show
  end

  # GET /form_editables/new
  def new
    @form_editable = FormEditable.new
  end

  # GET /form_editables/1/edit
  def edit
  end

  # POST /form_editables
  # POST /form_editables.json
  def create
    @form_editable = FormEditable.new(form_editable_params)

    respond_to do |format|
      if @form_editable.save
        format.html { redirect_to @form_editable, notice: 'Form editable was successfully created.' }
        format.json { render :show, status: :created, location: @form_editable }
      else
        format.html { render :new }
        format.json { render json: @form_editable.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /form_editables/1
  # PATCH/PUT /form_editables/1.json
  def update
    respond_to do |format|
      if @form_editable.update(form_editable_params)
        format.html { redirect_to @form_editable, notice: 'Form editable was successfully updated.' }
        format.json { render :show, status: :ok, location: @form_editable }
      else
        format.html { render :edit }
        format.json { render json: @form_editable.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /form_editables/1
  # DELETE /form_editables/1.json
  def destroy
    @form_editable.destroy
    respond_to do |format|
      format.html { redirect_to form_editables_url, notice: 'Form editable was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_form_editable
      @form_editable = FormEditable.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def form_editable_params
      params.require(:form_editable).permit(:down_payment_percentage, :max_payment_amount_limit, :months, :interest)
    end
end

app/helpers/form_editables_helper.rb
module FormEditablesHelper
end

app/views/form_editables/_form.html.erb
<%= form_with(model: form_editable, local: true) do |form| %>
  <% if form_editable.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(form_editable.errors.count, "error") %> prohibited this form_editable from being saved:</h2>

      <ul>
      <% form_editable.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :down_payment_percentage %>
    <%= form.number_field :down_payment_percentage %>
  </div>

  <div class="field">
    <%= form.label :max_payment_amount_limit %>
    <%= form.number_field :max_payment_amount_limit %>
  </div>

  <div class="field">
    <%= form.label :months %>
    <%= form.number_field :months %>
  </div>

  <div class="field">
    <%= form.label :interest %>
    <%= form.number_field :interest %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/form_editables/edit.html.erb
<h1>Editing Form Editable</h1>

<%= render 'form', form_editable: @form_editable %>

<%= link_to 'Show', @form_editable %> |
<%= link_to 'Back', form_editables_path %>

app/views/form_editables/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Form Editables</h1>

<table>
  <thead>
    <tr>
      <th>Down payment percentage</th>
      <th>Max payment amount limit</th>
      <th>Months</th>
      <th>Interest</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @form_editables.each do |form_editable| %>
      <tr>
        <td><%= form_editable.down_payment_percentage %></td>
        <td><%= form_editable.max_payment_amount_limit %></td>
        <td><%= form_editable.months %></td>
        <td><%= form_editable.interest %></td>
        <td><%= link_to 'Show', form_editable %></td>
        <td><%= link_to 'Edit', edit_form_editable_path(form_editable) %></td>
        <td><%= link_to 'Destroy', form_editable, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Form Editable', new_form_editable_path %>

app/views/form_editables/new.html.erb
<h1>New Form Editable</h1>

<%= render 'form', form_editable: @form_editable %>

<%= link_to 'Back', form_editables_path %>

app/views/form_editables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Down payment percentage:</strong>
  <%= @form_editable.down_payment_percentage %>
</p>

<p>
  <strong>Max payment amount limit:</strong>
  <%= @form_editable.max_payment_amount_limit %>
</p>

<p>
  <strong>Months:</strong>
  <%= @form_editable.months %>
</p>

<p>
  <strong>Interest:</strong>
  <%= @form_editable.interest %>
</p>

<%= link_to 'Edit', edit_form_editable_path(@form_editable) %> |
<%= link_to 'Back', form_editables_path %>