config/routes.rb
Rails.application.routes.draw do
  resources :form_editables
  devise_for :admins
  root :to => 'people#new'

  resources :people do
    resources :jobs
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PreapprovalProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <p class="navbar-text pull-right">
    <% if admin_signed_in? %>
      Logged in as <strong><%= current_admin.email %></strong>.
      <%= link_to 'Edit profile', edit_admin_registration_path, :class => 'navbar-link' %> |
      <%= link_to "Logout", destroy_admin_session_path, method: :delete, :class => 'navbar-link'  %>
    <% else %>
      <%= link_to "Sign up", new_admin_registration_path, :class => 'navbar-link'  %> |
      <%= link_to "Login", new_admin_session_path, :class => 'navbar-link'  %>
    <% end %>
    </p>
  </head>

  <body>

    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/layouts/customer_layout.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PreapprovalProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html>
<head>
<title>Preapproval Results</title>
  <%= wicked_pdf_stylesheet_link_tag "application" -%>
</head>
<body>

  <div class='container'>
    <%= yield %>
  </div>

</body>

<br><%= link_to 'Create PDF document', person_job_path(@job, :format => :pdf) %>

</html>